version: "3.8"
services:
  web:
    container_name: web
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    command:
      [
        "uvicorn",
        "--reload",
        "--host=0.0.0.0",
        "--port=8000",
        "src.main:app"
      ]

  db:
    image: postgres:16.1
    volumes:
      - db-data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
volumes:
  db-data:
